### ISSUE TITLE
Create a glossary of terms

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/nebula-guide#62]
# Overview

As a visitor to the Guide, I should be able to see a dictionary/glossary of all notable terms used in Guide (e.g. "Temoc") and their meaning (e.g. "The school mascot...").

# Proposal

There should be a single page on the website that contains a list of all notable terms in the UTD Survival Guide. This page should be accessible from the `/glossary` route (i.e. `https://utd.guide/glossary`)

Whoever implements this should come up with a schema for a `Glossary` object that stores `GlossaryEntry` objects that each have an associated `term` and `content`. The `term` and `content` should be stored in plain text.

## Supplementary Information

@SmokinTurkey should be able to create a mock-up for this. The page should display a list of all terms and their associated content.

In the future, the glossary may be able to support rich text formatting for content, but that is not necessary to implement this issue.

**Comment by Ron-Alex** [comment]
Mockup for the glossary page has been created in Figma. It is on the page 'Newer stuff' and is the frame 'Glossary page MVP.'

**Comment by WillieCubed** [comment]
I left a comment on the glossary page on Figma, but it looks like we still need some UI to actually add a term to the glossary database. Could you work on that?
