### ISSUE TITLE
Navigate to the landing page when clicking the site logo in header

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/nebula-guide#69]
# Overview

As a user, I should be able to click the site's logo in the header and be redirected to the home page.

# Proposal

Content-heavy websites usually allow the user to navigate to the home page by clicking an element in the navigation bar. The site should navigate to the index route (`/`) whenever the logo in the site header.

**Comment by vikranthchinnam** [comment]
Just did a PR to close the issue. I don't think there's any problems related to this issue anymore.

**Comment by WillieCubed** [comment]
Let's wait until the PR merges before closing the issue.
